name: Action DocC Archive
description: Archive your docc
inputs:
  host:
    description: '`--hosting-base-path` ex: "/sample"'
    required: true
    default: ''
  docc:
    description: 'The repo you test'
    required: true
  output:
    description: '`--output-path`'
    required: true
runs:
  using: 'composite'
  steps:
    - name: DocC Convert
      shell: bash
      run: |
        $(xcrun --find docc) convert \
            --hosting-base-path ${{inputs.host}} \
            --output-path Target.doccarchive \
            ${{inputs.docc}}
    - name: DocC Archive
      shell: bash
      run: |
          $(xcrun --find docc) process-archive transform-for-static-hosting Target.doccarchive \
            --hosting-base-path ${{inputs.host}} \
            --output-path ${{inputs.output}}
    
